# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 15:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=100, null=True)),
                ('lastName', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomFieldTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('value', models.CharField(blank=True, max_length=254, null=True)),
                ('customfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrike.CustomField')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('scope', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='wrike.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('briefDescription', models.CharField(blank=True, max_length=254, null=True)),
                ('importance', models.CharField(blank=True, max_length=100, null=True)),
                ('permalink', models.URLField(blank=True, max_length=254, null=True)),
                ('scope', models.CharField(blank=True, max_length=40, null=True)),
                ('createdDate', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(blank=True, null=True)),
                ('completedDate', models.DateTimeField(blank=True, null=True)),
                ('assignees', models.ManyToManyField(related_name='tasks', to='wrike.Contact')),
                ('customfields', models.ManyToManyField(through='wrike.CustomFieldTask', to='wrike.CustomField')),
                ('folders', models.ManyToManyField(related_name='tasks', to='wrike.Folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WrikeOauth2Credentials',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=20)),
                ('refresh_token', models.CharField(max_length=100)),
                ('last_time_access_token_fetched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customfieldtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrike.Task'),
        ),
    ]
