# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('ctype', models.CharField(blank=True, max_length=30, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('ctype', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customfield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrike.CustomField')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('scope', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_description', models.CharField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customfields', models.ManyToManyField(through='wrike.CustomFieldTask', to='wrike.CustomField')),
                ('folders', models.ManyToManyField(related_name='tasks', to='wrike.Folder')),
                ('responsible_ids', models.ManyToManyField(related_name='tasks', to='wrike.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='customfieldtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrike.Task'),
        ),
    ]
