# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 23:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('wrike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrikeOauth2Credentials',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('access_token', models.CharField(max_length=100)),
                ('token_type', models.CharField(max_length=20)),
                ('refresh_token', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_time_access_token_fetched', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
