# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrike', '0002_auto_20161116_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='assignees',
            field=models.ManyToManyField(related_name='projects', to='wrike.Contact'),
        ),
        migrations.AddField(
            model_name='folder',
            name='completedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
